# Generated by Django 4.1.7 on 2023-02-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doab_check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='provider',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='linkrel',
            name='role',
            field=models.CharField(default='identifier', max_length=10),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
