# Generated by Django 4.1.7 on 2023-04-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doab_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='content_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
