# Generated by Django 4.1.7 on 2023-04-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doab_check', '0002_alter_check_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='recent_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_link', to='doab_check.check'),
        ),
    ]
