# Generated by Django 4.1.7 on 2023-03-29 23:25
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('doab_check', '0002_link_provider_alter_linkrel_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='publisher_name',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),

    ]
