# Generated by Django 4.1.7 on 2023-03-30 14:19
import logging

from oaipmh.error import IdDoesNotExistError

from django.db import migrations
from doab_check.doab_oai import doab_client, unlist

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):
    def noop(apps, schema_editor):
        pass

    def getpub(apps, schema_editor):
        Item = apps.get_model('doab_check', 'Item')
        for item in Item.objects.all():
            try:
                record = doab_client.getRecord(
                    metadataPrefix='oai_dc',
                    identifier=item.doab
                )
                if not record[1]:
                    logger.error('No content in record %s', record)
                    return ''
                metadata = record[1].getMap()
                item.publisher_name = unlist(metadata.pop('publisher', ['']))
                item.save()
            except IdDoesNotExistError as e:
                logger.error(e)
                return ''

    dependencies = [
        ('doab_check', '0003_item_publisher_name'),
    ]

    operations = [
        migrations.RunPython(getpub, reverse_code=noop, hints={'doab_check': 'Item'}),
    ]
