# Generated by Django 4.1.7 on 2023-04-27 18:18

from django.db import migrations


def populate_recent(apps, schema_editor):
    Check = apps.get_model("doab_check", "Check")
    for check in Check.objects.order_by('created'):
        check.link.recent_check = check
        check.link.save()

class Migration(migrations.Migration):

    dependencies = [
        ('doab_check', '0003_link_recent_check'),
    ]

    operations = [
        migrations.RunPython(populate_recent),
    ]
