# Generated by Django 4.1.7 on 2023-09-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doab_check', '0004_auto_20230427_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='return_code',
            field=models.IntegerField(db_index=True),
        ),
    ]
