# Generated by Django 4.1.7 on 2023-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doab_check', '0004_auto_20230330_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='publisher_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
