# Generated by Django 4.1.7 on 2023-04-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doab_check', '0005_alter_item_publisher_name_alter_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
